version:  '3'

services:
  portainer:
    # container image definition
    image: portainer/portainer-ce:alpine
    # container name definition
    container_name: portainer_app
    # command definition
    command: -H unix:///var/run/docker.sock
    # restart policy definition
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    # volume mapping definition
    volumes:
    - /docker-services/portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: nproxy