version:  '3'

services:
  app:
    # container image definition
    image: jc21/nginx-proxy-manager:latest
    # container name definition
    container_name: nproxy_app
    # restart policy definition
    restart: always
    # port mapping definition
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    # volume mapping definition
    volumes:
      - /docker-services/nproxy/data:/data
      - /docker-services/nproxy/letsencrypt:/etc/letsencrypt
    # environment variable definintion
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: nproxy
      DB_MYSQL_USER: nproxy
      DB_MYSQL_PASSWORD: tmLZFnkfgOhLtPnB
      DISABLE_IPV6: 'true'
    # container dependencies
    depends_on:
      - db

  db:
    # container image definition
    image: 'jc21/mariadb-aria:latest'
    # container name definition
    container_name: nproxy_db
    # restart policy definition
    restart: always
    # volume mapping definition
    volumes:
      - /docker-services/nproxy/mysql:/var/lib/mysql
    # environment variable definintion
    environment:
      MYSQL_ROOT_PASSWORD: LvnuZcVAH03O17KL
      MYSQL_DATABASE: nproxy
      MYSQL_USER: nproxy
      MYSQL_PASSWORD: tmLZFnkfgOhLtPnB

networks:
  default:
    external:
      name: nproxy